events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
        
        location / {
            try_files $uri $uri/ /index.html;
        }
        
        location /dashboard {
            try_files $uri $uri/ /dashboard/index.html;
        }
        
        location /user-type {
            try_files $uri $uri/ /user-type/index.html;
        }
        
        location /login {
            try_files $uri $uri/ /login/index.html;
        }
    }
}
