apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-web
  template:
    metadata:
      labels:
        app: employee-web
    spec:
      containers:
        - name: employee-web
          image: ton-utilisateur/employee-web:latest
          ports:
            - containerPort: 80